http:
  routers:
    traefik:
      rule: "Host(`traefik.workflow_ci.localhost`)"
      middlewares:
        - "simpleAuth"
      service: "api@internal"
      tls:
        domains:
          - main: "workflow_ci.localhost"
            sans:
              - "*.workflow_ci.localhost"
  middlewares:
    simpleAuth:
      basicAuth:
        usersFile: "/etc/traefik/userFile"
tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
